services:
  api:
    build: .
    container_name: image-pipeline-api
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DATABASE_NAME=image_pipeline
      - UPLOAD_DIR=uploads
      - THUMBNAILS_DIR=thumbnails
      - BASE_URL=http://localhost:8000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - uploads_data:/app/uploads
      - thumbnails_data:/app/thumbnails
    restart: unless-stopped
    depends_on:
      - mongo
      - redis

  redis:
    image: redis:7-alpine
    container_name: image-pipeline-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  worker:
    build: .
    container_name: image-pipeline-worker
    command: celery -A app.worker.celery_app worker --loglevel=info
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DATABASE_NAME=image_pipeline
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - UPLOAD_DIR=uploads
      - THUMBNAILS_DIR=thumbnails
    volumes:
      - uploads_data:/app/uploads
      - thumbnails_data:/app/thumbnails
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: image-pipeline-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  uploads_data:
  thumbnails_data:
